repos:
  # generate 3rd libs
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config
        args: [ --application-directories=models,
                --application-directories=services,
                --application-directories=rpc_servicers,
                --application-directories=settings,
                --application-directories=server_grpc,
                --application-directories=server_fast_api,
        ]
        exclude: migrations
  # sorting imports
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.5.4 # Use the revision sha / tag you want to point at
    hooks:
      - id: isort
        args: [ "--profile", "black" ]
        exclude: migrations
  # reformat code
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3.11
  # validate PEP8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: debug-statements
      - id: check-merge-conflict
        exclude: migrations,hosting
